/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2016-06-25 03:40:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_002dhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/materialize.css\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/mystyle.css\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/admin.css\"/>\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/drag.css\"/>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/animate.css\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--Let browser know website is optimized for mobile-->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body class=\"purple lighten-5\">\r\n");
      out.write("  <div class=\"wrapper\">\r\n");
      out.write("        <header class=\"headnav\">\r\n");
      out.write("                        <ul id=\"slide-out\" class=\"side-nav fixed z-depth-0\">\r\n");
      out.write("                          <div class=\"center\">\r\n");
      out.write("                              <img src=\"./img/logo.png\" class=\"circle\" style=\"width: 100%; height: 100%; margin-top: 40px; margin-bottom: 20px;\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                          <li><a href=\"admin-home.jsp\" class=\"waves-effect\"><b>Home</b></a></li>\r\n");
      out.write("                         <!--  <li class=\"no-padding\"> -->\r\n");
      out.write("                            <ul class=\"collapsible\" data-collapsible=\"accordion\">\r\n");
      out.write("                              <li>\r\n");
      out.write("                                <a class=\"collapsible-header\"><b>Maintenance</b></a>\r\n");
      out.write("                                  <div class=\"collapsible-body\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                      <li><a href=\"employeeMaintenance\">Employee</a></li>\r\n");
      out.write("                                      <li><a href=\"productServiceMaintenance\">Product & Service</a></li>\r\n");
      out.write("                                      <li><a href=\"catalogueMaintenance\">Catalogue</a></li>\r\n");
      out.write("                                      <li><a href=\"packageMaintenance\">Package</a></li>\r\n");
      out.write("                                      <li><a href=\"locationMaintenance\">Delivery Charge</a></li>\r\n");
      out.write("                                      <li><a href=\"extraChargeMaintenance\">Other Charge</a></li>\r\n");
      out.write("                                      <li><a href=\"promoMaintenance\">Promo</a></li>\r\n");
      out.write("                                      <li><a href=\"discountMaintenance\">Discount</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li>\r\n");
      out.write("                                <a class=\"collapsible-header\"><b>Transaction</b></a>\r\n");
      out.write("                                  <div class=\"collapsible-body\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                      <li><a href=\"getInventory\">Inventory</a></li>\r\n");
      out.write("                                      <li><a href=\"transactions-reservation.jsp\">Reservation</a></li>\r\n");
      out.write("                                      <li><a href=\"transactions-productorder.jsp\">Product Order</a></li>\r\n");
      out.write("                                      <li><a href=\"transactions-vip.jsp\">VIP</a></li>\r\n");
      out.write("                                      <li><a href=\"transactions-walkin.jsp\">Walk In</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                              </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          <li><a href=\"utilities.jsp\" class=\"waves-effect\"><b>Utilities</b></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                       <nav class=\"z-depth-0\">\r\n");
      out.write("                         <div class=\"nav-wrapper purple darken-4\">\r\n");
      out.write("                           <a href=\"#!\" class=\"brand-logo purple-text text-lighten-5\" style=\"margin-left: 30px;\">Salon Management System</a>\r\n");
      out.write("                         \r\n");
      out.write("                           <a href=\"#\" data-activates=\"mobile-demo\" class=\"button-collapse\"><i class=\"material-icons\">menu</i></a>\r\n");
      out.write("                           <ul class=\"side-nav\" id=\"mobile-demo\">\r\n");
      out.write("                             <li><a href=\"admin-home.jsp\" class=\"waves-effect waves-orange\"><b>Home</b></a></li>\r\n");
      out.write("                               <ul class=\"collapsible collapsible-accordion\">\r\n");
      out.write("                                 <li>\r\n");
      out.write("                                   <a class=\"waves-effect waves-orange collapsible-header\"><b>Maintenance</b></a>\r\n");
      out.write("                                     <div class=\"collapsible-body\">\r\n");
      out.write("                                       <ul>\r\n");
      out.write("                                         <li><a href=\"maintenance-emp.jsp\">Employee</a></li>\r\n");
      out.write("                                         <li><a href=\"maintenance-prodsvc.jsp\">Product & Service</a></li>\r\n");
      out.write("                                         <li><a href=\"maintenance-promo.jsp\">Promo</a></li>\r\n");
      out.write("                                         <li><a href=\"maintenance-discount.jsp\">Discount</a></li>\r\n");
      out.write("                                         <li><a href=\"maintenance-package.jsp\">Package</a></li>\r\n");
      out.write("                                         <li><a href=\"maintenance-catalogue.jsp\">Catalogue</a></li>\r\n");
      out.write("                                         <li><a href=\"maintenance-extra.jsp\">Extra Charge</a></li>\r\n");
      out.write("                                       </ul>\r\n");
      out.write("                                     </div>\r\n");
      out.write("                                 </li>\r\n");
      out.write("                                 <li>\r\n");
      out.write("                                   <a class=\"waves-effect waves-orange collapsible-header\"><b>Transaction</b></a>\r\n");
      out.write("                                     <div class=\"collapsible-body\">\r\n");
      out.write("                                       <ul>\r\n");
      out.write("                                         <li><a href=\"transactions-inventory.jsp\">Inventory</a></li>\r\n");
      out.write("                                         <li><a href=\"transactions-reservation.jsp\">Reservation</a></li>\r\n");
      out.write("                                         <li><a href=\"transactions-productorder.jsp\">Product Order</a></li>\r\n");
      out.write("                                         <li><a href=\"#!\">Walk-In</a></li>\r\n");
      out.write("                                       </ul>\r\n");
      out.write("                                     </div>\r\n");
      out.write("                                 </li>\r\n");
      out.write("                               </ul>\r\n");
      out.write("                              <li><a href=\"utilities.jsp\" class=\"waves-effect waves-orange\"><b>Utilities</b></a></li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                         </div>\r\n");
      out.write("                       </nav>\r\n");
      out.write("                </header>\r\n");
      out.write("\r\n");
      out.write("                <article>\r\n");
      out.write("                <div class=\"wrapper\">\r\n");
      out.write("                  <div class=\"col s12 center\" style=\"margin-top: 200px;\">\r\n");
      out.write("                    <button id=\"welcome\" class=\"btn waves-effect waves-light purple darken-3 animated infinite rubberBand z-depth-3\" style=\"width: 300px; height: 150px;font-size: 30px;\">WELCOME</button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- <article>\r\n");
      out.write("          <div class=\"wrapper\">\r\n");
      out.write("                    <div class=\"aside aside1 z-depth-1\">\r\n");
      out.write("                      <header><h5>Add Employee</h5></header>\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                          <form class=\"col s12\" action=\"\">\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("                                  <div class=\"input-field col s6 offset-s6\">\r\n");
      out.write("                                      <img  id=\"output1\" style=\"width: 120px; height: 120px;\" src=\"./img/anon.jpg\" alt=\"\"/>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s4\">\r\n");
      out.write("                                      <input id=\"empid\" type=\"text\" disabled=\"disabled\">\r\n");
      out.write("                                      <label for=\"empid\">Employee ID</label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s7 offset-s1\">\r\n");
      out.write("                                      <div class=\"file-field\">\r\n");
      out.write("                                            <div class=\"btn orange\">\r\n");
      out.write("                                              <span class=\"\">File</span>\r\n");
      out.write("                                              <input type=\"file\" accept=\"image/*\" onchange=\"loadFile(event)\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"file-path-wrapper\">\r\n");
      out.write("                                              <input class=\"file-path validate\" type=\"text\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s12\">\r\n");
      out.write("                                      <input id=\"fname\" type=\"text\" class=\"validate\">\r\n");
      out.write("                                      <label for=\"fname\">First Name</label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s6\">\r\n");
      out.write("                                      <input id=\"mname\" type=\"text\" class=\"validate\">\r\n");
      out.write("                                      <label for=\"mname\">Middle Name</label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s6\">\r\n");
      out.write("                                      <input id=\"lname\" type=\"text\" class=\"validate\">\r\n");
      out.write("                                      <label for=\"lname\">Last Name</label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s12\">\r\n");
      out.write("                                      <div class=\"input-field col s4\">\r\n");
      out.write("                                          <select>\r\n");
      out.write("                                            <option value=\"\" disabled selected>Month</option>\r\n");
      out.write("                                            <option value=\"1\">January</option>\r\n");
      out.write("                                            <option value=\"2\">February</option>\r\n");
      out.write("                                            <option value=\"3\">March</option>\r\n");
      out.write("                                            <option value=\"4\">April</option>\r\n");
      out.write("                                            <option value=\"5\">May</option>\r\n");
      out.write("                                            <option value=\"6\">June</option>\r\n");
      out.write("                                            <option value=\"7\">July</option>\r\n");
      out.write("                                            <option value=\"8\">August</option>\r\n");
      out.write("                                            <option value=\"9\">September</option>\r\n");
      out.write("                                            <option value=\"10\">October</option>\r\n");
      out.write("                                            <option value=\"11\">November</option>\r\n");
      out.write("                                            <option value=\"12\">December</option>\r\n");
      out.write("                                          </select>\r\n");
      out.write("                                          <label>Birthday</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"input-field col s2\">\r\n");
      out.write("                                          <input type=\"text\" id=\"day\" class=\"validate\" maxlength=\"2\" style=\"margin-left: -25px;\">\r\n");
      out.write("                                          <label for=\"day\" style=\"margin-left: -10px;\">Day</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"input-field col s2\">\r\n");
      out.write("                                          <input type=\"text\" id=\"year\" class=\"validate\" maxlength=\"4\" style=\"margin-left: -50px;\">\r\n");
      out.write("                                          <label for=\"year\" style=\"margin-left: -25px;\">Year</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"input-field col s4\">\r\n");
      out.write("                                            <input type=\"text\" id=\"age\" class=\"validate\" maxlength=\"3\" disabled=\"disabled\">\r\n");
      out.write("                                            <label for=\"age\">Age</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s6\">\r\n");
      out.write("                                      <p>   \r\n");
      out.write("                                            <input class=\"with-gap\" name=\"group1\" type=\"radio\" id=\"Male\" value=\"Male\" />\r\n");
      out.write("                                            <label for=\"Male\">Male</label>\r\n");
      out.write("                                            <input class=\"with-gap\" name=\"group1\" type=\"radio\" id=\"Female\" value=\"Female\" />\r\n");
      out.write("                                            <label for=\"Female\">Female</label>\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s1\">\r\n");
      out.write("                                    <p style=\"margin-top: 12px; margin-left: -9px;\">(+63)</p>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s5\">\r\n");
      out.write("                                      <input type=\"text\" id=\"contact\" class=\"validate\" maxlength=\"10\">\r\n");
      out.write("                                      <label for=\"contact\">Contact Number</label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s12\">\r\n");
      out.write("                                      <input type=\"text\" id=\"address\" class=\"validate\">\r\n");
      out.write("                                      <label for=\"address\">Address</label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s12\">\r\n");
      out.write("                                      <select multiple>\r\n");
      out.write("                                        <option value=\"\" disabled selected>Choose Position:</option>\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                      </select>\r\n");
      out.write("                                      <label>Position:</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                  <a class=\"modal-trigger waves-effect waves-white btn-flat orange\" title=\"Next\" href=\"#modal1\">NEXT</a>\r\n");
      out.write("                                  <button class=\"waves-effect waves-orange btn-flat white\" type=\"reset\" value=\"Reset\" title=\"Clear\">CLEAR</button>\r\n");
      out.write("                              </div>\r\n");
      out.write("\r\n");
      out.write("                              Modal Structure\r\n");
      out.write("                                <div id=\"modal1\" class=\"modal modal-fixed-footer\" style=\"width: 450px; height: 450px;\">\r\n");
      out.write("                                  <div class=\"modal-content\">\r\n");
      out.write("                                    <h4>Employee Account</h4>\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col s12\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                              <div class=\"input-field col s8 offset-s2\">\r\n");
      out.write("                                                <input id=\"username\" type=\"text\" class=\"validate\">\r\n");
      out.write("                                                <label for=\"username\">Username</label>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <div class=\"input-field col s8 offset-s2\">\r\n");
      out.write("                                                <input id=\"password\" type=\"password\" class=\"validate\">\r\n");
      out.write("                                                <label for=\"password\">Password</label>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <div class=\"input-field col s8 offset-s2\">\r\n");
      out.write("                                                <input id=\"conf-password\" type=\"password\" class=\"validate\" onkeyup=\"checkPass(); return false;\">\r\n");
      out.write("                                                <label for=\"conf-password\">Confirm Password</label>\r\n");
      out.write("                                                <span id=\"confirmMsg\" class=\"confirmMsg\"></span>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <div class=\"input-field col s8 offset-s2\">\r\n");
      out.write("                                                <p id=\"pass-error\"></p>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"modal-footer\">\r\n");
      out.write("                                    <a href=\"#!\" class=\"modal-action modal-close waves-effect waves-green btn-flat \">CANCEL</a>\r\n");
      out.write("                                    <button href=\"#!\" class=\"modal-action waves-effect waves-green btn-flat orange\" id=\"savebtn\" disabled=\"disabled\">SAVE</button>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                          </form>\r\n");
      out.write("                      </div>\r\n");
      out.write("\r\n");
      out.write("                     \r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"aside aside2 z-depth-1\">\r\n");
      out.write("                      EDIT/DELETE/VIEW Employee\r\n");
      out.write("                      edit/delete/view employee\r\n");
      out.write("                    </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </article> -->\r\n");
      out.write("        <div id=\"draggable\" class=\"ui-widget-content fixed-action-btn horizontal transparent\" style=\"border:0px !important; bottom: 45px; right: 24px; z-index: 100000px;\">\r\n");
      out.write("          <a class=\"btn-floating btn-large red\">\r\n");
      out.write("                <i class=\"large material-icons\">mode_edit</i>\r\n");
      out.write("              </a>\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><a class=\"btn-floating red\"><i class=\"material-icons\">insert_chart</i></a></li>\r\n");
      out.write("                <li><a class=\"btn-floating yellow darken-1\"><i class=\"material-icons\">format_quote</i></a></li>\r\n");
      out.write("                <li><a class=\"btn-floating green\"><i class=\"material-icons\">publish</i></a></li>\r\n");
      out.write("                <li><a class=\"btn-floating blue\"><i class=\"material-icons\">attach_file</i></a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        </article>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  <!--Import jQuery before materialize.js-->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/materialize.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/drag.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("      $( document ).ready(function(){\r\n");
      out.write("        $(\".button-collapse\").sideNav();\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("      $(function() {\r\n");
      out.write("        $( \"#draggable\" ).draggable();\r\n");
      out.write("      });\r\n");
      out.write("      </script>\r\n");
      out.write("\r\n");
      out.write("      <script type=\"text/javascript\">\r\n");
      out.write("      $('#welcome').addClass('animated infinite rubberBand');\r\n");
      out.write("      </script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Upload image -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /admin-home.jsp(199,40) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/admin-home.jsp(199,40) '${empCategory}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${empCategory}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /admin-home.jsp(199,40) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("name");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                          \t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name.strCategoryName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name.strCategoryName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\r\n");
          out.write("                                          ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
