/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2016-06-25 06:16:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class calendar_002dview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./css/materialize.min.css\"  media=\"screen,projection\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/materialize.css\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/mystyle.css\"/>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/datatables.min.css\"/>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/datatables.material.min.css\"/>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/material.min.css\">\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/trans-reservation.css\"/><!--Let browser know website is optimized for mobile-->\r\n");
      out.write("  <!-- full calendar declrations -->\r\n");
      out.write("  <link href='./css/fullcalendar.css' rel='stylesheet' />\r\n");
      out.write("  <link href='./css/fullcalendar.print.css' rel='stylesheet' media='print' />\r\n");
      out.write("  <script src='./js/moment.min.js'></script>\r\n");
      out.write("  <script src='./js/jquery.min.js'></script>\r\n");
      out.write("  <script src='./js/fullcalendar.min.js'></script>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("\r\n");
      out.write("   $(document).ready(function() {\r\n");
      out.write("     \r\n");
      out.write("     $('#calendar').fullCalendar({\r\n");
      out.write("       header: {\r\n");
      out.write("         left: 'prev,next today',\r\n");
      out.write("         center: 'title',\r\n");
      out.write("         right: 'month,basicWeek,basicDay'\r\n");
      out.write("       },\r\n");
      out.write("       defaultDate: '2016-01-12',\r\n");
      out.write("       editable: true,\r\n");
      out.write("       eventLimit: true, // allow \"more\" link when too many events\r\n");
      out.write("       events: [\r\n");
      out.write("         {\r\n");
      out.write("           title: 'All Day Event',\r\n");
      out.write("           start: '2016-01-01'\r\n");
      out.write("         },\r\n");
      out.write("         {\r\n");
      out.write("           title: 'Long Event',\r\n");
      out.write("           start: '2016-01-07',\r\n");
      out.write("           end: '2016-01-10'\r\n");
      out.write("         },\r\n");
      out.write("         {\r\n");
      out.write("           id: 999,\r\n");
      out.write("           title: 'Repeating Event',\r\n");
      out.write("           start: '2016-01-09T16:00:00'\r\n");
      out.write("         },\r\n");
      out.write("         {\r\n");
      out.write("           id: 999,\r\n");
      out.write("           title: 'Repeating Event',\r\n");
      out.write("           start: '2016-01-16T16:00:00'\r\n");
      out.write("         },\r\n");
      out.write("         {\r\n");
      out.write("           title: 'Conference',\r\n");
      out.write("           start: '2016-01-11',\r\n");
      out.write("           end: '2016-01-13'\r\n");
      out.write("         },\r\n");
      out.write("         {\r\n");
      out.write("           title: 'Meeting',\r\n");
      out.write("           start: '2016-01-12T10:30:00',\r\n");
      out.write("           end: '2016-01-12T12:30:00'\r\n");
      out.write("         },\r\n");
      out.write("         {\r\n");
      out.write("           title: 'Lunch',\r\n");
      out.write("           start: '2016-01-12T12:00:00'\r\n");
      out.write("         },\r\n");
      out.write("         {\r\n");
      out.write("           title: 'Meeting',\r\n");
      out.write("           start: '2016-01-12T14:30:00'\r\n");
      out.write("         },\r\n");
      out.write("         {\r\n");
      out.write("           title: 'Happy Hour',\r\n");
      out.write("           start: '2016-01-12T17:30:00'\r\n");
      out.write("         },\r\n");
      out.write("         {\r\n");
      out.write("           title: 'Dinner',\r\n");
      out.write("           start: '2016-01-12T20:00:00'\r\n");
      out.write("         },\r\n");
      out.write("         {\r\n");
      out.write("           title: 'Birthday Party',\r\n");
      out.write("           start: '2016-01-13T07:00:00'\r\n");
      out.write("         },\r\n");
      out.write("         {\r\n");
      out.write("           title: 'Click for Google',\r\n");
      out.write("           url: 'http://google.com/',\r\n");
      out.write("           start: '2016-01-28'\r\n");
      out.write("         }\r\n");
      out.write("       ]\r\n");
      out.write("     });\r\n");
      out.write("     \r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("  </script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("  #calendar {\r\n");
      out.write("    max-width: 900px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body class=\"blue-grey lighten-5\">\r\n");
      out.write("    <nav class=\"z-depth-0\">\r\n");
      out.write("      <div class=\"nav-wrapper purple\">\r\n");
      out.write("        <a href=\"#!\" class=\"brand-logo white-text\" style=\"margin-left: 30px;\">Salon Management System</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"container white z-depth-barts\">\r\n");
      out.write("      <h1 class=\"thin center purple-text text-darken-4\">\r\n");
      out.write("        Calendar View\r\n");
      out.write("      </h1>\r\n");
      out.write("      <div class=\"col s3\" style=\"margin-left: 28px; margin-bottom: 5px;\">\r\n");
      out.write("      <a href=\"transactions-reservation.jsp\" class=\" z-depth-barts waves-effect waves-light purple btn-flat white-text\">Back</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"wrapper\">\r\n");
      out.write("                 <div id='calendar'></div>  \r\n");
      out.write("          </div>\r\n");
      out.write("    </div>\r\n");
      out.write("          \r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
