/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2016-06-25 03:39:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./css/materialize.min.css\"  media=\"screen,projection\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/materialize.css\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/mystyle.css\"/>\r\n");
      out.write("    <!--Let browser know website is optimized for mobile-->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body style=\"background: url(./img/login.jpg) no-repeat; background-size: 100%; \" class=\"responsive-img\">\r\n");
      out.write("    \r\n");
      out.write("        <header>  \r\n");
      out.write("          <div class=\"navbar-fixed\">\r\n");
      out.write("            <nav class=\"white z-depth-barts\">\r\n");
      out.write("              <div class=\"container\">\r\n");
      out.write("                  <div class=\"nav-wrapper\">\r\n");
      out.write("                    <a href=\"#\" class=\"brand-logo grey-text\">Generic Salon System</a>\r\n");
      out.write("                    <ul class=\"right hide-on-med-and-down\">\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("          </div>\r\n");
      out.write("        </header>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("            <aside class=\"aside aside-1 z-depth-barts\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                        <form class=\"col s12\" action=\"login\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"center\">\r\n");
      out.write("                                  <h3>Login</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-field col s8 offset-s2\">\r\n");
      out.write("                                  <input type=\"text\" name=\"username\" id=\"username\" class=\"validate\">\r\n");
      out.write("                                  <label for=\"id\">Username</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-field col s8 offset-s2\">\r\n");
      out.write("                                  <input type=\"password\" name=\"pass\" id=\"pass\" class=\"validate\">\r\n");
      out.write("                                  <label for=\"pass\">Password</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col s12\" style=\"margin-top: 50px;\">\r\n");
      out.write("                                  <button class=\"waves-effect waves-light orange btn-flat\" type=\"submit\" value=\"Submit\" id=\"submitbtn\">Login</button>\r\n");
      out.write("                                  <a href=\"#\" class=\"waves-effect waves-orange btn-flat\" onclick=\"loginform.jsp\">Back</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </aside>\r\n");
      out.write("            <!-- <main class=\"main\">\r\n");
      out.write("            </main> -->\r\n");
      out.write("            <aside class=\"aside aside-2 z-depth-barts\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col s12\" style=\"margin-top: 50px;\">\r\n");
      out.write("                    <h1>Welcome</h1>\r\n");
      out.write("                    <p>MEHEHEHE</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col s12\" style=\"margin-top: 50px; margin-bottom: 60px;\">\r\n");
      out.write("                    <a href=\"#\" class=\"waves-effect waves-light orange btn\">Continue as Guest</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </aside>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\\\r\n");
      out.write("    body, html, footer {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .wrapper {\r\n");
      out.write("      display: -webkit-box;\r\n");
      out.write("      display: -moz-box;\r\n");
      out.write("      display: -ms-flexbox;\r\n");
      out.write("      display: -webkit-flex;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: row;\r\n");
      out.write("      \r\n");
      out.write("      -webkit-flex-flow: row wrap;\r\n");
      out.write("      flex-flow: row wrap;\r\n");
      out.write("      -moz-flex-flow: row wrap;\r\n");
      out.write("      -o-flex-flow: row wrap;\r\n");
      out.write("    }\r\n");
      out.write("    .wrapper > * {\r\n");
      out.write("      flex: 1 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .aside-1{\r\n");
      out.write("      background: white;\r\n");
      out.write("      border-radius: 3px;\r\n");
      out.write("      margin: 10px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      width: 50px;\r\n");
      out.write("      height: 30%;\r\n");
      out.write("    }\r\n");
      out.write("    .aside-2{\r\n");
      out.write("      background: white;\r\n");
      out.write("      border-radius: 3px;\r\n");
      out.write("      margin: 10px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      width: 50px;\r\n");
      out.write("      height: 30%;\r\n");
      out.write("    }\r\n");
      out.write("    @media all and (min-width: 600px) {\r\n");
      out.write("      /* We tell both sidebars to share a row */\r\n");
      out.write("      .aside { flex: 1 auto; }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Large screens */\r\n");
      out.write("    @media all and (min-width: 800px) {\r\n");
      out.write("       /*We invert order of first sidebar and main\r\n");
      out.write("       * And tell the main element to take twice as much width as the other two sidebars \r\n");
      out.write("       */\r\n");
      out.write("      .main { flex: 2 0px; }\r\n");
      out.write("      \r\n");
      out.write("      .aside-1 { order: 1; }\r\n");
      out.write("      .main    { order: 2; }\r\n");
      out.write("      .aside-2 { order: 3; }\r\n");
      out.write("      .footer  { order: 4; }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!--Import jQuery before materialize.js-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/materialize.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("  <footer class=\"footer page-footer white z-depth-barts\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col l6 s12\">\r\n");
      out.write("              <h5 class=\"orange-text text-darken-3\">Follow us!</h5>\r\n");
      out.write("              <p class=\"orange-text text-darken-3\">Like, share, learn!</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col l4 offset-l2 s12\">\r\n");
      out.write("              <h5>Links</h5>\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><a class=\"orange-text text-darken-3\" href=\"#!\">www.facebook.com/GenericSalonSystem</a></li>\r\n");
      out.write("                <li><a class=\"orange-text text-darken-3\" href=\"#!\">www.twitter.com/@GenericSalonSystem</a></li>\r\n");
      out.write("                <li><a class=\"orange-text text-darken-3\" href=\"#!\">www.GenericSalonSystem.com</a></li>\r\n");
      out.write("                <li><a class=\"orange-text text-darken-3\" href=\"#!\">www.instagram.com/@GenericSalonSystem</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-copyright\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("            <span class=\"orange-text text-darken-3\">(c) 2015 Copyright</span>\r\n");
      out.write("            <a class=\"orange-text text-darken-3 right\" href=\"#!\">More Links</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
