/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2016-06-25 05:39:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gss.model.Location;

public final class maintenance_002dlocation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html ng-app>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/materialize.css\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/mystyle.css\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/mtnc-promo.css\"/>\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/bartstable.css\"/>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/material.min.css\"/>\r\n");
      out.write("\r\n");
      out.write("    <!--Let browser know website is optimized for mobile-->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body class=\"purple lighten-5\">\r\n");
      out.write("  <div class=\"wrapper\">\r\n");
      out.write("            <header class=\"headnav\">\r\n");
      out.write("                <ul id=\"slide-out\" class=\"side-nav fixed z-depth-0\">\r\n");
      out.write("                  <div class=\"center\">\r\n");
      out.write("                      <img src=\"./img/logo.png\" class=\"circle\" style=\"width: 100%; height: 100%; margin-top: 40px; margin-bottom: 20px;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  <li><a href=\"admin-home.jsp\" class=\"waves-effect\"><b>Home</b></a></li>\r\n");
      out.write("                 <!--  <li class=\"no-padding\"> -->\r\n");
      out.write("                    <ul class=\"collapsible\" data-collapsible=\"accordion\">\r\n");
      out.write("                      <li>\r\n");
      out.write("                        <a class=\"collapsible-header active\"><b>Maintenance</b></a>\r\n");
      out.write("                          <div class=\"collapsible-body\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                              <li><a href=\"employeeMaintenance\">Employee</a></li>\r\n");
      out.write("                              <li><a href=\"productServiceMaintenance\">Product & Service</a></li>\r\n");
      out.write("                              <li><a href=\"catalogueMaintenance\">Catalogue</a></li>\r\n");
      out.write("                              <li><a href=\"packageMaintenance\">Package</a></li>\r\n");
      out.write("                              <li class=\"purple lighten-4\"><a href=\"locationMaintenance\">Delivery Charge</a></li>\r\n");
      out.write("                              <li><a href=\"extraChargeMaintenance\">Other Charge</a></li>\r\n");
      out.write("                              <li><a href=\"promoMaintenance\">Promo</a></li>\r\n");
      out.write("                              <li><a href=\"discountMaintenance\">Discount</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li>\r\n");
      out.write("                        <a class=\"collapsible-header\"><b>Transaction</b></a>\r\n");
      out.write("                          <div class=\"collapsible-body\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                              <li><a href=\"transactions-inventory.jsp\">Inventory</a></li>\r\n");
      out.write("                              <li><a href=\"transactions-reservation.jsp\">Reservation</a></li>\r\n");
      out.write("                              <li><a href=\"transactions-productorder.jsp\">Product Order</a></li>\r\n");
      out.write("                              <li><a href=\"transactions-vip.jsp\">VIP</a></li>\r\n");
      out.write("                              <li><a href=\"transactions-walkin.jsp\">Walk In</a></li>\r\n");
      out.write("                              </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  <li><a href=\"utilities.jsp\" class=\"waves-effect\"><b>Utilities</b></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("               <nav class=\"z-depth-0\">\r\n");
      out.write("                 <div class=\"nav-wrapper purple darken-4\">\r\n");
      out.write("                   <a href=\"#!\" class=\"brand-logo purple-text text-lighten-5\" style=\"margin-left: 30px;\">Salon Management System</a>\r\n");
      out.write("                 \r\n");
      out.write("                   <a href=\"#\" data-activates=\"mobile-demo\" class=\"button-collapse\"><i class=\"material-icons\">menu</i></a>\r\n");
      out.write("                   <ul class=\"side-nav\" id=\"mobile-demo\">\r\n");
      out.write("                     <li><a href=\"admin-home.jsp\" class=\"waves-effect\"><b>Home</b></a>\r\n");
      out.write("                       <ul class=\"collapsible collapsible-accordion\">\r\n");
      out.write("                         <li>\r\n");
      out.write("                           <a class=\"waves-effectcollapsible-header\"><b>Maintenance</b></a>\r\n");
      out.write("                             <div class=\"collapsible-body\">\r\n");
      out.write("                               <ul>\r\n");
      out.write("                                 <li><a href=\"employeeMaintenance\">Employee</a></li>\r\n");
      out.write("                                      <li><a href=\"productServiceMaintenance\">Product & Service</a></li>\r\n");
      out.write("                                      <li><a href=\"maintenance-package.jsp\">Package</a></li>\r\n");
      out.write("                                      <li><a href=\"catalogueMaintenance\">Catalogue</a></li>\r\n");
      out.write("                                      <li><a href=\"promoMaintenance\">Promo</a></li>\r\n");
      out.write("                                      <li><a href=\"discountMaintenance\">Discount</a></li>\r\n");
      out.write("                                      <li><a href=\"extraChargeMaintenance\">Charge</a></li>\r\n");
      out.write("                                      <li class=\"purple lighten-4\"><a href=\"maintenance-location.jsp\">Location</a></li>\r\n");
      out.write("                               </ul>\r\n");
      out.write("                             </div>\r\n");
      out.write("                         </li>\r\n");
      out.write("                         <li>\r\n");
      out.write("                           <a class=\"waves-effectcollapsible-header\"><b>Transaction</b></a>\r\n");
      out.write("                             <div class=\"collapsible-body\">\r\n");
      out.write("                               <ul>\r\n");
      out.write("                                 <li><a href=\"transactions-inventory.jsp\">Inventory</a></li>\r\n");
      out.write("                                 <li><a href=\"transactions-reservation.jsp\">Reservation</a></li>\r\n");
      out.write("                                 <li><a href=\"transactions-vip.jsp\">VIP</a></li>\r\n");
      out.write("                                 <li><a href=\"transactions-productorder.jsp\">Product Order</a></li>\r\n");
      out.write("                                 <li><a href=\"transactions-walkin.jsp\">Walk-In</a></li>\r\n");
      out.write("                               </ul>\r\n");
      out.write("                             </div>\r\n");
      out.write("                         </li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                    <li><a href=\"utilities.jsp\" class=\"waves-effect\"><b>Utilities</b></a></li>\r\n");
      out.write("                   </ul>\r\n");
      out.write("                 </div>\r\n");
      out.write("               </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <article>\r\n");
      out.write("        <!-- <div class=\"container\"> -->\r\n");
      out.write("          <div class=\"wrapper\">\r\n");
      out.write("<!--                     <div class=\"aside aside1 z-depth-barts\">\r\n");
      out.write("                    \r\n");
      out.write("                    </div> -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"main z-depth-barts\" style=\"margin-left: 20px; margin-right: 20px;\">\r\n");
      out.write("                        <div class=\"col s12\" style=\"margin-left: 20px; margin-right: 20px;\">\r\n");
      out.write("                        <h3 class=\"grey-text text-darken-1\">Delivery Charge Maintenance</h3>\r\n");
      out.write("                        <a data-delay=\"30\" data-position=\"bottom\" data-tooltip=\"Create\" class=\"waves-effect waves-light modal-trigger btn-flat purple darken-3 left white-text tooltipped\" href=\"#create\" style=\"margin-top: 50px; margin-left: 15px;\"><i class=\"material-icons\">add</i></a>\r\n");
      out.write("                        <a data-delay=\"30\" data-position=\"bottom\" data-tooltip=\"Archive\" class=\"waves-effect waves-light modal-trigger btn-flat purple darken-3 left white-text tooltipped\" href=\"#archive\" style=\"margin-top: 50px; margin-left: 15px;\"><i class=\"material-icons\">archive</i></a>\r\n");
      out.write("                        <table id=\"example\" class=\"display centered responsive-table highlight\" cellspacing=\"0\" width=\"100%\" style=\"border: 1px solid #bdbdbd; padding: 10px;\" rowspan=\"10\">\r\n");
      out.write("                                <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th><center>Location</center></th>\r\n");
      out.write("                                        <th><center>Price</center></th>\r\n");
      out.write("                                        <th><center>Action</center></th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                   <!--  <tr>\r\n");
      out.write("                                        <td>1</td>\r\n");
      out.write("                                        <td>Additional 20km</td>\r\n");
      out.write("                                        <td>20km +</td>\r\n");
      out.write("                                        <td>01/01/01</td>\r\n");
      out.write("                                        <td><a class=\"waves-effect waves-light modal-trigger btn-flat transparent black-text\" title=\"Update\" href=\"#update\" style=\"padding: 0px;\"><i class=\"material-icons\">edit</i></a>\r\n");
      out.write("                                        <a class=\"waves-effect waves-light modal-trigger btn-flat transparent red-text text-accent-4\" href=\"#delete\" title=\"Deactivate\"><i class=\"material-icons\">delete</i></a>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr> -->\r\n");
      out.write("                                    ");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /maintenance-location.jsp(134,36) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/maintenance-location.jsp(134,36) '${locationList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${locationList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /maintenance-location.jsp(134,36) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("loc");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                      <tr>\r\n");
            out.write("                                      ");

                                          Location loca = (Location)pageContext.getAttribute("loc");
                                          int id = loca.getIntLocationID();
                                      
            out.write("\r\n");
            out.write("\r\n");
            out.write("                                        <td style=\"padding:0; margin:0;\"><center>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loc.strLocationName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</center></td>\r\n");
            out.write("                                        <td style=\"padding:0; margin:0;\"><center>Php ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loc.dblLocationPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</center></td>\r\n");
            out.write("                                        <td class=\"center\" style=\"padding:0; margin:0;\"><center>\r\n");
            out.write("                                        <!-- <a data-delay=\"30\" data-position=\"bottom\" data-tooltip=\"View\" class=\"tooltipped waves-effect waves-light modal-trigger btn-flat transparent black-text\" href=\"#viewLocation\" style=\"padding-left: 10px;padding-right:10px; margin: 5px;\">\r\n");
            out.write("                                        <i class=\"material-icons\">visibility</i></a> -->\r\n");
            out.write("                                        <a data-delay=\"30\" data-position=\"bottom\" data-tooltip=\"Update\" class=\"tooltipped waves-effect waves-light modal-trigger btn-flat transparent black-text\" href=\"#upd");
            out.print(id);
            out.write("\" style=\"padding-left: 10px;padding-right:10px; margin: 5px;\">\r\n");
            out.write("                                        <i class=\"material-icons\">edit</i></a>\r\n");
            out.write("                                        <a data-delay=\"30\" data-position=\"bottom\" data-tooltip=\"Deactivate\" class=\"tooltipped waves-effect waves-light modal-trigger btn-flat transparent red-text text-accent-4\" href=\"#del");
            out.print(id);
            out.write("\" style=\"padding-left: 10px;padding-right:10px; margin: 5px;\">\r\n");
            out.write("                                        <i class=\"material-icons\">delete</i></a></center>\r\n");
            out.write("                                        </td>\r\n");
            out.write("                                      </tr>\r\n");
            out.write("                                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      }
      out.write("\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("\r\n");
      out.write("                      <!-- Modal Structure -->\r\n");
      out.write("                        <div id=\"create\" class=\"modal modal-fixed-footer\">\r\n");
      out.write("                        <form class=\"col s12\" id=\"createExtraForm\" method=\"post\" action=\"createLocation\">\r\n");
      out.write("                          <div class=\"modal-content\">\r\n");
      out.write("                            <!-- <div class=\"container\"> -->\r\n");
      out.write("                              <div class=\"wrapper\">\r\n");
      out.write("                                  <h4 class=\"grey-text text-darken-1\" style=\"margin-bottom: 40px;\">Create Location</h4>\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                            <div class=\"input-field col s12\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("                                                <label class=\"red-text\"> (*) Indicates required field</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"input-field col s12\" style=\"margin-top: 25px;\">\r\n");
      out.write("                                                <input type=\"text\" class=\"validate tooltipped specialname\" id=\"createLocationName\"\r\n");
      out.write("                                                name=\"strLocationName\" required pattern=\"^[a-zA-Z\\-.\\s]{5,}$\" minlength=\"5\" maxlength=\"15\" data-delay=\"30\" data-position=\"bottom\" data-tooltip=\"Ex: Sta. Mesa<br/>( At least 5 or more characters )\" placeholder=\"LocationName\">\r\n");
      out.write("                                                <label for=\"createLocationName\" class=\"active\">Location Name<span class=\"red-text\">*</span></label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"input-field col s6\">\r\n");
      out.write("                                                <input id=\"createEChargeDesc\" name=\"dblLocationPrice\" class=\"materialize-textarea tooltipped\" maxlength=\"15\" required minlength=\"1\" data-delay=\"30\" data-position=\"bottom\" data-tooltip=\"Base Price\" placeholder=\"Price\">\r\n");
      out.write("                                                <label for=\"createEChargeDesc\" class=\"active\">Price<span class=\"red-text\">*</span></label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"modal-footer\">\r\n");
      out.write("                              <button type=\"reset\" value=\"Reset\" class=\"modal-action modal-close waves-effect waves-purple transparent btn-flat\">CANCEL</button>\r\n");
      out.write("                              <button class=\"waves-effect waves-light purple darken-3 white-text btn-flat\" type=\"submit\" value=\"Submit\">CREATE</button>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                      ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        ");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /maintenance-location.jsp(217,24) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/maintenance-location.jsp(217,24) '${locationList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${locationList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /maintenance-location.jsp(217,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("loc");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                          ");

                                        
                              Location loca = (Location)pageContext.getAttribute("loc");
                                          int id = loca.getIntLocationID();
                         
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("                          <div id=\"del");
            out.print(id);
            out.write("\" class=\"modal\" style=\"width: 30% !important;\">\r\n");
            out.write("                          <form action=\"deactivateLocation\" method=\"get\">\r\n");
            out.write("                          <div class=\"container\">\r\n");
            out.write("                            <input type=\"hidden\" name=\"intLocationID\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loc.intLocationID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\">\r\n");
            out.write("                            <div class=\"modal-content\">\r\n");
            out.write("                              <div class=\"row\">\r\n");
            out.write("                                <h5 class=\"red-text\">Warning!</h5>\r\n");
            out.write("                                <p class=\"center\">Are you sure you want to deactivate</p>\r\n");
            out.write("                                <p class=\"center\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loc.strLocationName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("?</p>\r\n");
            out.write("                              </div>\r\n");
            out.write("                            </div>\r\n");
            out.write("                              <div class=\"col s12 center\" style=\"margin-bottom: 30px;\">\r\n");
            out.write("                                <button class=\"waves-effect waves-light purple btn-flat white-text\">YES</button>\r\n");
            out.write("                                <a href=\"#\" class=\"modal-action modal-close waves-effect waves-light transparent btn-flat black-text\">NO</a>\r\n");
            out.write("                              </div>\r\n");
            out.write("                            </div>\r\n");
            out.write("                          </form>\r\n");
            out.write("                      </div>\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      }
      out.write("\r\n");
      out.write("<!--                     <div class=\"aside aside2 z-depth-barts\">\r\n");
      out.write("                     \r\n");
      out.write("                    </div> -->\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      <!-- </div> -->\r\n");
      out.write("        </article>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  #create {\r\n");
      out.write("    width: 30% !important;\r\n");
      out.write("    height: 70% !important;\r\n");
      out.write("    max-height: 100% !important;\r\n");
      out.write("  }\r\n");
      out.write("  #update{\r\n");
      out.write("    width: 30% !important;\r\n");
      out.write("    height: 70% !important;\r\n");
      out.write("    max-height: 100% !important;\r\n");
      out.write("  }\r\n");
      out.write("  #viewProdSvc {\r\n");
      out.write("    width: 40% !important;\r\n");
      out.write("  }\r\n");
      out.write("  .error {\r\n");
      out.write("    color: red;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  </style>\r\n");
      out.write("\r\n");
      out.write("  <!--Import jQuery before materialize.js-->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/materialize.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/angular.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/maintenance-emp.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/bartstable.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/jquery.validate.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/validation.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /maintenance-location.jsp(188,22) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/maintenance-location.jsp(188,22) '${locationList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${locationList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /maintenance-location.jsp(188,22) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("loc");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <div id=\"upd");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loc.intLocationID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"modal modal-fixed-footer\" style=\"width: 30% !important; height: 70% !important; max-height: 100% !important;\">\r\n");
          out.write("                        <form class=\"col s12\" method=\"get\" id=\"u\" class=\"updateExtraForm\" action=\"updateLocation\">\r\n");
          out.write("                          <div class=\"modal-content\">\r\n");
          out.write("                            <!-- <div class=\"container\"> -->\r\n");
          out.write("                              <div class=\"wrapper\">\r\n");
          out.write("                                  <h4 class=\"grey-text text-darken-1\" style=\"margin-bottom: 40px;\">Update Location</h4>\r\n");
          out.write("                                    <div class=\"row\">\r\n");
          out.write("                                            <div class=\"input-field col s12\">\r\n");
          out.write("                                                <input type=\"hidden\" name=\"intLocationID\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loc.intLocationID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">\r\n");
          out.write("\r\n");
          out.write("                                                <input id=\"updateLocationName\" name=\"strLocationName\" type=\"text\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loc.strLocationName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"validate tooltipped specialname\" pattern=\"^[a-zA-Z\\-.\\s]{5,}$\" placeholder=\"Location Name\" data-delay=\"30\" data-position=\"bottom\" data-tooltip=\"Ex: Sta. Mesa\" minlength=\"5\" maxlength=\"15\">\r\n");
          out.write("                                                <label for=\"updateLocationName\" class=\"active\">Location</label>\r\n");
          out.write("                                            </div>\r\n");
          out.write("                                            <div class=\"input-field col s6\">\r\n");
          out.write("                                                <input id=\"updateLocationPrice\" name=\"dblLocationPrice\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loc.dblLocationPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"materialize-textarea tooltipped\" data-delay=\"30\" data-position=\"bottom\" data-tooltip=\"Ex: 99.99\" maxlength=\"30\" minlength=\"5\">\r\n");
          out.write("                                                <label for=\"updateLocationPrice\" class=\"active\">Price</label>\r\n");
          out.write("                                            </div>\r\n");
          out.write("                                    </div>\r\n");
          out.write("                              </div>\r\n");
          out.write("                          </div>\r\n");
          out.write("                          <div class=\"modal-footer\">\r\n");
          out.write("                              <button type=\"reset\" value=\"Reset\" class=\"modal-action modal-close waves-effect waves-purple transparent btn-flat\">CANCEL</button>\r\n");
          out.write("                              <button class=\"waves-effect waves-light purple darken-3 white-text btn-flat\" type=\"submit\" value=\"Submit\">UPDATE</button>\r\n");
          out.write("                          </div>\r\n");
          out.write("                          </form>\r\n");
          out.write("                    </div>\r\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }
}
