/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2016-06-25 07:13:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class transactions_002dinventory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html ng-app>\r\n");
      out.write("\t\r\n");
      out.write("  \r\n");
      out.write("  <head>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./css/materialize.min.css\"  media=\"screen,projection\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/materialize.css\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/mystyle.css\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/mtnc-catalogue.css\"/>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/bartstable.css\"/>\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/material.min.css\"/>\r\n");
      out.write("\r\n");
      out.write("    <!--Let browser know website is optimized for mobile-->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body class=\"blue-grey lighten-5\">\r\n");
      out.write("  <div class=\"wrapper\">\r\n");
      out.write("        <header class=\"headnav\">\r\n");
      out.write("                        <ul id=\"slide-out\" class=\"side-nav fixed z-depth-0\">\r\n");
      out.write("                          <div class=\"center\">\r\n");
      out.write("                              <img src=\"./img/logo.png\" class=\"circle\" style=\"width: 100%; height: 100%; margin-top: 40px; margin-bottom: 20px;\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                          <li><a href=\"admin-home.jsp\" class=\"waves-effect\"><b>Home</b></a></li>\r\n");
      out.write("                         <!--  <li class=\"no-padding\"> -->\r\n");
      out.write("                            <ul class=\"collapsible\" data-collapsible=\"accordion\">\r\n");
      out.write("                              <li>\r\n");
      out.write("                                <a class=\"collapsible-header\"><b>Maintenance</b></a>\r\n");
      out.write("                                  <div class=\"collapsible-body\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                      <li><a href=\"employeeMaintenance\">Employee</a></li>\r\n");
      out.write("                                      <li><a href=\"productServiceMaintenance\">Product & Service</a></li>\r\n");
      out.write("                                      <li><a href=\"catalogueMaintenance\">Catalogue</a></li>\r\n");
      out.write("                                      <li><a href=\"packageMaintenance\">Package</a></li>\r\n");
      out.write("                                      <li><a href=\"locationMaintenance\">Delivery Charge</a></li>\r\n");
      out.write("                                      <li><a href=\"extraChargeMaintenance\">Other Charge</a></li>\r\n");
      out.write("                                      <li><a href=\"promoMaintenance\">Promo</a></li>\r\n");
      out.write("                                      <li><a href=\"discountMaintenance\">Discount</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li>\r\n");
      out.write("                                <a class=\"collapsible-header active\"><b>Transaction</b></a>\r\n");
      out.write("                                  <div class=\"collapsible-body\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                      <li class=\"purple lighten-4\"><a href=\"transactions-inventory.jsp\">Inventory</a></li>\r\n");
      out.write("                                      <li><a href=\"transactions-reservation.jsp\">Reservation</a></li>\r\n");
      out.write("                                      <li><a href=\"transactions-productorder.jsp\">Product Order</a></li>\r\n");
      out.write("                                      <li><a href=\"transactions-vip.jsp\">Payment</a></li>\r\n");
      out.write("                                      <li><a href=\"transactions-walkin.jsp\">Walk In</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                              </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          <li><a href=\"utilities.jsp\" class=\"waves-effect\"><b>Utilities</b></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                       <nav class=\"z-depth-0\">\r\n");
      out.write("                         <div class=\"nav-wrapper purple\">\r\n");
      out.write("                           <a href=\"#!\" class=\"brand-logo white-text\" style=\"margin-left: 30px;\">Salon Management System</a>\r\n");
      out.write("                         \r\n");
      out.write("                           <a href=\"#\" data-activates=\"mobile-demo\" class=\"button-collapse\"><i class=\"material-icons\">menu</i></a>\r\n");
      out.write("                           <ul class=\"side-nav\" id=\"mobile-demo\">\r\n");
      out.write("                             <li><a href=\"admin-home.jsp\" class=\"waves-effect waves-purple\"><b>Home</b></a>\r\n");
      out.write("                               <ul class=\"collapsible collapsible-accordion\">\r\n");
      out.write("                                 <li>\r\n");
      out.write("                                   <a class=\"collapsible-header\"><b>Maintenance</b></a>\r\n");
      out.write("                                     <div class=\"collapsible-body\">\r\n");
      out.write("                                       <ul>\r\n");
      out.write("                                         <li><a href=\"maintenance-emp.jsp\">Employee</a></li>\r\n");
      out.write("                                         <li><a href=\"maintenance-prodsvc.jsp\">Product & Service</a></li>\r\n");
      out.write("                                         <li><a href=\"maintenance-promo.jsp\">Promo</a></li>\r\n");
      out.write("                                         <li><a href=\"maintenance-discount.jsp\">Discount</a></li>\r\n");
      out.write("                                         <li><a href=\"maintenance-package.jsp\">Package</a></li>\r\n");
      out.write("                                         <li><a href=\"maintenance-catalogue.jsp\">Catalogue</a></li>\r\n");
      out.write("                                         <li><a href=\"maintenance-extra.jsp\">Extra Charge</a></li>\r\n");
      out.write("                                       </ul>\r\n");
      out.write("                                     </div>\r\n");
      out.write("                                 </li>\r\n");
      out.write("                                 <li>\r\n");
      out.write("                                   <a class=\"collapsible-header active\"><b>Transaction</b></a>\r\n");
      out.write("                                     <div class=\"collapsible-body\">\r\n");
      out.write("                                       <ul>\r\n");
      out.write("                                         <li class=\"purple\"><a href=\"transactions-inventory.jsp\">Inventory</a></li>\r\n");
      out.write("                                         <li><a href=\"transactions-reservation.jsp\">Reservation</a></li>\r\n");
      out.write("                                         <li><a href=\"transactions-productorder.jsp\">Product Order</a></li>\r\n");
      out.write("                                         <li><a href=\"#!\">Walk-In</a></li>\r\n");
      out.write("                                       </ul>\r\n");
      out.write("                                     </div>\r\n");
      out.write("                                 </li>\r\n");
      out.write("                               </ul>\r\n");
      out.write("                             <li><a href=\"utilities.jsp\" class=\"waves-effect waves-purple\"><b>Utilities</b></a></li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                         </div>\r\n");
      out.write("                       </nav>\r\n");
      out.write("                </header>\r\n");
      out.write("\r\n");
      out.write("        <article>\r\n");
      out.write("          <div class=\"wrapper\">\r\n");
      out.write("                              \r\n");
      out.write("                      <div class=\"aside aside2 z-depth-barts\">\r\n");
      out.write("                             <div class=\"col s12\" style=\"margin-left: 20px; margin-right: 20px;\">\r\n");
      out.write("                             <h3 class=\"grey-text text-darken-1\">Inventory</h3>\r\n");
      out.write("                             <div class=\"row\">\r\n");
      out.write("                               <div class=\"input-field col s4\">\r\n");
      out.write("                               <h4 class=\"thin\">Filter by:</h4>\r\n");
      out.write("                                 <select name=\"categoty\" required>\r\n");
      out.write("                                   <option value=\"\" disabled selected>Inventory category</option>  \r\n");
      out.write("                                     <option value=\"}\">Expired</option>\r\n");
      out.write("                                     <option value=\"}\">Lost</option>\r\n");
      out.write("                                     <option value=\"}\">Defect</option>\r\n");
      out.write("                                 </select>\r\n");
      out.write("                               </div>\r\n");
      out.write("                             </div>\r\n");
      out.write("                             \r\n");
      out.write("                             <a class=\"tooltipped waves-effect waves-light modal-trigger btn-flat purple darken-3 left white-text\" href=\"#defectiveitem\" style=\"margin-top: 50px; margin-left: 15px;\" data-delay=\"30\" data-position=\"bottom\" data-tooltip=\"Defective Item\"><i class=\"material-icons\">broken_image</i></a>\r\n");
      out.write("                             <a class=\"tooltipped waves-effect waves-light modal-trigger btn-flat purple darken-3 left white-text\" href=\"#lostitem\" style=\"margin-top: 50px; margin-left: 15px;\" data-delay=\"30\" data-position=\"bottom\" data-tooltip=\"Lost Item\"><i class=\"material-icons\">search</i></a>\r\n");
      out.write("                             <a class=\"tooltipped waves-effect waves-light modal-trigger btn-flat purple darken-3 left white-text\" href=\"#expireditem\" style=\"margin-top: 50px; margin-left: 15px;\" data-delay=\"30\" data-position=\"bottom\" data-tooltip=\"Expired Item\"><i class=\"material-icons\">event_busy</i></a>\r\n");
      out.write("                             <a class=\"tooltipped waves-effect waves-light modal-trigger btn-flat purple darken-3 left white-text\" href=\"#archive\" style=\"margin-top: 50px; margin-left: 15px;\" data-delay=\"30\" data-position=\"bottom\" data-tooltip=\"Expired Item\"><i class=\"material-icons\">system_update_alt</i></a>\r\n");
      out.write("\r\n");
      out.write("                             <table id=\"example\" class=\"display centered responsive-table highlight\" cellspacing=\"0\" width=\"100%\" style=\"border: 1px solid #bdbdbd; padding: 10px;\" rowspan=\"10\">\r\n");
      out.write("                                     <thead>\r\n");
      out.write("                                         <tr>\r\n");
      out.write("                                             <th><center>Name</center></th>\r\n");
      out.write("                                             <th><center>Selling Price</center></th>\r\n");
      out.write("                                             <th><center>Stock</center></th>\r\n");
      out.write("                                             <th><center>Date/Time</center></th>\r\n");
      out.write("                                             <th><center>Actions</center></th>\r\n");
      out.write("                                         </tr>\r\n");
      out.write("                                     </thead>\r\n");
      out.write("                                     <tbody>\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                     </tbody>\r\n");
      out.write("                                 </table>\r\n");
      out.write("                           </div>                    \r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"archive\" class=\"modal modal-fixed-footer\" style=\"width: 90% !important; margin-bottom: 0px !important; height: 50% !important; max-height: 100% !important;\">\r\n");
      out.write("                          <form class=\"col s12\" name=\"DamagedForm\" method=\"post\" action=\"createTag\">\r\n");
      out.write("                              <div class=\"modal-content\">\r\n");
      out.write("                                <div class=\"wrapper\">\r\n");
      out.write("                                  <h4 class=\"grey-text text-darken-1\"><center>Archive</center></h4>\r\n");
      out.write("                                  <div class=\"row\">\r\n");
      out.write("                                      <table id=\"example\" class=\"display centered responsive-table highlight\" cellspacing=\"0\" width=\"100%\" style=\"border: 1px solid #bdbdbd; padding: 10px;\" rowspan=\"10\">\r\n");
      out.write("                                              <thead>\r\n");
      out.write("                                                  <tr>\r\n");
      out.write("                                                      <th><center>Name</center></th>\r\n");
      out.write("                                                      <th><center>Selling Price</center></th>\r\n");
      out.write("                                                      <th><center>Quantity</center></th>\r\n");
      out.write("                                                      <th><center>Date/Time</center></th>\r\n");
      out.write("                                                      <th><center>Actions</center></th>\r\n");
      out.write("                                                  </tr>\r\n");
      out.write("                                              </thead>\r\n");
      out.write("                                              <tbody>\r\n");
      out.write("                                                 ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                              </tbody>\r\n");
      out.write("                                          </table>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"modal-footer\">\r\n");
      out.write("                                <button type=\"submit\" class=\"waves-effect waves-white btn-flat purple white-text\">SAVE</button>\r\n");
      out.write("                                <a href=\"#!\" class=\"modal-action modal-close waves-effect waves-purple btn-flat \">CANCEL</a>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"defectiveitem\" class=\"modal modal-fixed-footer\" style=\"width: 30% !important; margin-bottom: 0px !important; height: 50% !important; max-height: 100% !important;\">\r\n");
      out.write("                          <form class=\"col s12\" name=\"DamagedForm\" method=\"post\" action=\"createTag\">\r\n");
      out.write("                              <div class=\"modal-content\">\r\n");
      out.write("                                <div class=\"wrapper\">\r\n");
      out.write("                                  <h4 class=\"grey-text text-darken-1\"><center>Defective Item</center></h4>\r\n");
      out.write("                                  <div class=\"row\">\r\n");
      out.write("                                    <div class=\"input-field col s12\" style=\"margin-top: 10%;\">\r\n");
      out.write("                                      <select name=\"intProductID\" required>\r\n");
      out.write("                                        <option value=\"\" disabled selected>Item Name</option>  \r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                      </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"input-field col s12\" style=\"margin-top: 5%;\">\r\n");
      out.write("                                      <input type=\"number\" name=\"intQuantity\" id=\"Quantity\" maxlength=\"3\" placeholder=\"1\" pattern=\"^[0-9]$\" min=\"1\" required></input>\r\n");
      out.write("                                      <label for=\"Quantity\">Quantity</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("<!-- ///// IMPORTANT CODES /////////  DO NOT EDIT /////////////////////////////////////////////////////////-->\r\n");
      out.write("                                    <div class=\"input-field col s12\" style=\"margin-top: 5%;\">\r\n");
      out.write("                                      <input type=\"hidden\" name=\"intTagType\" id=\"tagType\" value=\"1\"></input>\r\n");
      out.write("                                    </div>\r\n");
      out.write("<!-- /////////////////////////////////////////////////////////////////////////////////////////////////-->\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"modal-footer\">\r\n");
      out.write("                                <button type=\"submit\" class=\"waves-effect waves-white btn-flat purple white-text\">SAVE</button>\r\n");
      out.write("                                <a href=\"#!\" class=\"modal-action modal-close waves-effect waves-purple btn-flat \">CANCEL</a>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"lostitem\" class=\"modal modal-fixed-footer\" style=\"width: 30% !important; height: 50% !important; max-height: 100% !important;\">\r\n");
      out.write("                          <form class=\"col s12\" name=\"LostForm\" method=\"post\" action=\"createTag\">\r\n");
      out.write("                              <div class=\"modal-content\">\r\n");
      out.write("                                <div class=\"wrapper\">\r\n");
      out.write("                                  <h4 class=\"grey-text text-darken-1\"><center>Lost Item</center></h4>\r\n");
      out.write("                                  <div class=\"row\">\r\n");
      out.write("                                    <div class=\"input-field col s12\" style=\"margin-top: 10%;\">\r\n");
      out.write("                                      <select name=\"intProductID\" required>\r\n");
      out.write("                                        <option value=\"\" disabled selected>Item Name</option>  \r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                      </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"input-field col s12\" style=\"margin-top: 5%;\">\r\n");
      out.write("                                      <input type=\"number\" name=\"intQuantity\" id=\"Quantity\" maxlength=\"3\" placeholder=\"1\" pattern=\"^[0-9]$\" min=\"1\" required></input>\r\n");
      out.write("                                      <label for=\"Quantity\">Quantity</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("<!-- ///// IMPORTANT CODES /////////  DO NOT EDIT /////////////////////////////////////////////////////////-->\r\n");
      out.write("                                    <div class=\"input-field col s12\" style=\"margin-top: 5%;\">\r\n");
      out.write("                                      <input type=\"hidden\" name=\"intTagType\" id=\"tagType\" value=\"2\"></input>\r\n");
      out.write("                                    </div>\r\n");
      out.write("<!-- /////////////////////////////////////////////////////////////////////////////////////////////-->\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"modal-footer\">\r\n");
      out.write("                                <button type=\"submit\" class=\"waves-effect waves-white btn-flat purple white-text\">SAVE</button>\r\n");
      out.write("                                <a href=\"#!\" class=\"modal-action modal-close waves-effect waves-purple btn-flat \">CANCEL</a>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"expireditem\" class=\"modal modal-fixed-footer\" style=\"width: 30% !important; height: 50% !important; max-height: 100% !important;\">\r\n");
      out.write("                          <form class=\"col s12\" name=\"ExpiredForm\" method=\"post\" action=\"createTag\">\r\n");
      out.write("                              <div class=\"modal-content\">\r\n");
      out.write("                                <div class=\"wrapper\">\r\n");
      out.write("                                  <h4 class=\"grey-text text-darken-1\"><center>Expired Item</center></h4>\r\n");
      out.write("                                  <div class=\"row\">\r\n");
      out.write("                                    <div class=\"input-field col s12\" style=\"margin-top: 10%;\">\r\n");
      out.write("                                      <select name=\"intProductID\" required>\r\n");
      out.write("                                        <option value=\"\" disabled selected>Item Name</option>  \r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fforEach_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                      </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"input-field col s12\" style=\"margin-top: 5%;\">\r\n");
      out.write("                                      <input type=\"number\" name=\"intQuantity\" id=\"Quantity\" maxlength=\"3\" placeholder=\"1\" pattern=\"^[0-9]$\" min=\"1\" required></input>\r\n");
      out.write("                                      <label for=\"Quantity\">Quantity</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("<!-- ///// IMPORTANT CODES /////////  DO NOT EDIT /////////////////////////////////////////////////////////-->\r\n");
      out.write("                                    <div class=\"input-field col s12\" style=\"margin-top: 5%;\">\r\n");
      out.write("                                      <input type=\"hidden\" name=\"intTagType\" id=\"tagType\" value=\"3\"></input>\r\n");
      out.write("                                    </div>\r\n");
      out.write("<!-- //////////////////////////////////////////////////////////////////////////////////////////////////////-->                                    \r\n");
      out.write("                                  </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"modal-footer\">\r\n");
      out.write("                                <button type=\"submit\" class=\"waves-effect waves-white btn-flat purple white-text\">SAVE</button>\r\n");
      out.write("                                <a href=\"#!\" class=\"modal-action modal-close waves-effect waves-purple btn-flat \">CANCEL</a>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                      ");
      if (_jspx_meth_c_005fforEach_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </article>\r\n");
      out.write("           <!-- Modal Structure -->\r\n");
      out.write("  </div>\r\n");
      out.write("                \r\n");
      out.write("  <!--Import jQuery before materialize.js-->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/materialize.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/maintenance-emp.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/angular.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/bartstable.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("        $('ul.tabs').tabs('select_tab', 'add');\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /transactions-inventory.jsp(134,40) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/transactions-inventory.jsp(134,40) '${productList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${productList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /transactions-inventory.jsp(134,40) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("product");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                         <tr>\r\n");
          out.write("                                             <td style=\"padding:0; margin:0;\"><center>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.strProductName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</center></td>\r\n");
          out.write("                                             <td style=\"padding:0; margin:0;\"><center>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.dblProductPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</center></td>\r\n");
          out.write("                                             <td style=\"padding:0; margin:0;\"><center>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductQuantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</center></td>\r\n");
          out.write("                                             <td style=\"padding:0; margin:0;\"><center>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductQuantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</center></td>\r\n");
          out.write("                                             <td class=\"center\" style=\"padding:0; margin:0;\"><center>\r\n");
          out.write("                                             <a class=\"tooltipped waves-effect waves-light modal-trigger btn-flat transparent black-text\" title=\"Update\" href=\"#inventoryedit");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" style=\"padding-left: 10px;padding-right:10px; margin: 5px;\" data-delay=\"30\" data-position=\"bottom\" data-tooltip=\"Update\"><i class=\"material-icons\">edit</i></a></center>\r\n");
          out.write("                                             </td>\r\n");
          out.write("                                         </tr>\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /transactions-inventory.jsp(167,49) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/transactions-inventory.jsp(167,49) '${productList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${productList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /transactions-inventory.jsp(167,49) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("product");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                                  <tr>\r\n");
          out.write("                                                      <td style=\"padding:0; margin:0;\"><center>Wax</center></td>\r\n");
          out.write("                                                      <td style=\"padding:0; margin:0;\"><center>P200/center></td>\r\n");
          out.write("                                                      <td style=\"padding:0; margin:0;\"><center>35</center></td>\r\n");
          out.write("                                                      <td style=\"padding:0; margin:0;\"><center>12/23/17</center></td>\r\n");
          out.write("                                                      <td class=\"center\" style=\"padding:0; margin:0;\"><center>\r\n");
          out.write("                                                      <a class=\"tooltipped waves-effect waves-light modal-trigger btn-flat transparent black-text\" title=\"Update\" href=\"#inventoryedit");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" style=\"padding-left: 10px;padding-right:10px; margin: 5px;\" data-delay=\"30\" data-position=\"bottom\" data-tooltip=\"Update\"><i class=\"material-icons\">edit</i></a></center>\r\n");
          out.write("                                                      </td>\r\n");
          out.write("                                                  </tr>\r\n");
          out.write("                                                 ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /transactions-inventory.jsp(198,40) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/transactions-inventory.jsp(198,40) '${productList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${productList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /transactions-inventory.jsp(198,40) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("product");
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("                                          <option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.strProductName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f3.setParent(null);
    // /transactions-inventory.jsp(232,40) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/transactions-inventory.jsp(232,40) '${productList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${productList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /transactions-inventory.jsp(232,40) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setVar("product");
    int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
      if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("                                          <option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.strProductName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f3.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f4.setParent(null);
    // /transactions-inventory.jsp(266,40) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f4.setItems(new org.apache.jasper.el.JspValueExpression("/transactions-inventory.jsp(266,40) '${productList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${productList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /transactions-inventory.jsp(266,40) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f4.setVar("product");
    int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
      if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("                                          <option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.strProductName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f4.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f5 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f5.setParent(null);
    // /transactions-inventory.jsp(290,22) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f5.setItems(new org.apache.jasper.el.JspValueExpression("/transactions-inventory.jsp(290,22) '${productList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${productList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /transactions-inventory.jsp(290,22) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f5.setVar("product");
    int[] _jspx_push_body_count_c_005fforEach_005f5 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f5 = _jspx_th_c_005fforEach_005f5.doStartTag();
      if (_jspx_eval_c_005fforEach_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <div id=\"inventoryedit");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"modal modal-fixed-footer\" style=\"width: 30% !important; height: 65% !important; max-height: 100% !important;\">\r\n");
          out.write("                              <div class=\"col s12\">\r\n");
          out.write("                                <ul class=\"tabs\">\r\n");
          out.write("                                  <li class=\"tab col s6\"><a href=\"#add");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">Increase Stock</a></li>\r\n");
          out.write("                                  <li class=\"tab col s6\"><a  class=\"active\" href=\"#subtract");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">Decrease Stock</a></li>\r\n");
          out.write("                                </ul>\r\n");
          out.write("                              </div>\r\n");
          out.write("                              <div id=\"add");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"col s12\">\r\n");
          out.write("                                <form class=\"col s12\" name=\"addForm\" method=\"post\" action=\"updateStock\">\r\n");
          out.write("                                <div class=\"modal-content\">\r\n");
          out.write("                                  <div class=\"row\">\r\n");
          out.write("\r\n");
          out.write("<!-- ///// IMPORTANT CODES /////////  DO NOT EDIT /////////////////////////////////////////////////////////-->\r\n");
          out.write("                                      <input type=\"hidden\" name=\"intProductID\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">\r\n");
          out.write("                                      <input type=\"hidden\" name=\"intType\" value=\"1\">\r\n");
          out.write("<!--///////////////////////////////////////////////////////////////////////////////////////////////////////-->\r\n");
          out.write("                                    <div class=\"input-field col s8 offset-s2\" style=\"margin-top: 5%;\">\r\n");
          out.write("                                      <input type=\"text\" id=\"prodname\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.strProductName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" disabled style=\"color: black !important;\">\r\n");
          out.write("                                      <label for=\"prodname\" style=\"color: black !important;\">Product Name</label>\r\n");
          out.write("                                    </div>\r\n");
          out.write("                                    <div class=\"input-field col s8 offset-s2\" style=\"margin-top: 5%;\">\r\n");
          out.write("                                      <input type=\"number\" id=\"addcurrentstock\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductQuantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" min=\"0\" max=\"3\" disabled style=\"color: black;\">\r\n");
          out.write("                                      <label for=\"addcurrentstock\" class=\"active black-text\">Current Stock</label>\r\n");
          out.write("                                    </div>\r\n");
          out.write("                                    <div class=\"input-field col s8 offset-s2\" style=\"margin-top: 5%;\">\r\n");
          out.write("                                      <input name=\"intQuantity\" type=\"number\" id=\"addstocknumber\" placeholder=\"1\" min=\"0\">\r\n");
          out.write("                                      <label for=\"addstocknumber\" class=\"active\">Stock (<b>+</b>)</label>\r\n");
          out.write("                                    </div>\r\n");
          out.write("                                    <div class=\"input-field col s8 offset-s2\" style=\"margin-top: 5%;\">\r\n");
          out.write("                                      <input class=\"black-text\" type=\"number\" id=\"addtotalstock\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductQuantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" min=\"0\" disabled>\r\n");
          out.write("                                      <label for=\"addtotalstock\" class=\"active black-text\">Total Stock</label>\r\n");
          out.write("                                    </div>\r\n");
          out.write("                                  </div>\r\n");
          out.write("                                </div>\r\n");
          out.write("                                <div class=\"modal-footer\">\r\n");
          out.write("                                  <button type=\"submit\" class=\"waves-effect waves-white btn-flat purple white-text\">SAVE</button>\r\n");
          out.write("                                  <a href=\"#!\" class=\"modal-action modal-close waves-effect waves-purple btn-flat \">CANCEL</a>\r\n");
          out.write("                                </div>\r\n");
          out.write("                                </form>\r\n");
          out.write("                              </div>\r\n");
          out.write("\r\n");
          out.write("                              <div id=\"subtract");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"col s12\">\r\n");
          out.write("                                <form class=\"col s12\" name=\"subForm\" action=\"updateStock\" method=\"post\">\r\n");
          out.write("                                <div class=\"modal-content\">\r\n");
          out.write("                                  <div class=\"row\">\r\n");
          out.write("\r\n");
          out.write("<!-- ///// IMPORTANT CODES /////////  DO NOT EDIT /////////////////////////////////////////////////////////-->\r\n");
          out.write("                                      <input type=\"hidden\" name=\"intProductID\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">\r\n");
          out.write("                                      <input type=\"hidden\" name=\"intType\" value=\"2\"> \r\n");
          out.write("<!--///////////////////////////////////////////////////////////////////////////////////////////////////////-->                                    \r\n");
          out.write("\r\n");
          out.write("                                    <div class=\"input-field col s8 offset-s2\" style=\"margin-top: 5%;\">\r\n");
          out.write("                                      <input type=\"text\" id=\"subprodname\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.strProductName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" disabled style=\"color: black !important;\">\r\n");
          out.write("                                      <label for=\"subprodname\" style=\"color: black !important;\">Product Name</label>\r\n");
          out.write("                                    </div>\r\n");
          out.write("                                    <div class=\"input-field col s8 offset-s2\" style=\"margin-top: 5%;\">\r\n");
          out.write("                                      <input type=\"number\" id=\"subcurrentstock\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductQuantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" min=\"0\" max=\"3\" disabled style=\"color: black;\">\r\n");
          out.write("                                      <label for=\"subcurrentstock\" class=\"active black-text\">Current Stock</label>\r\n");
          out.write("                                    </div>\r\n");
          out.write("                                    <div class=\"input-field col s8 offset-s2\" style=\"margin-top: 5%;\">\r\n");
          out.write("                                      <input name=\"intQuantity\" type=\"number\" id=\"substocknumber\" placeholder=\"1\" min=\"0\">\r\n");
          out.write("                                      <label for=\"substocknumber\" class=\"active\">Stock (<b>-</b>)</label>\r\n");
          out.write("                                    </div>\r\n");
          out.write("                                    <div class=\"input-field col s8 offset-s2\" style=\"margin-top: 5%;\">\r\n");
          out.write("                                      <input class=\"black-text\" type=\"number\" id=\"subtotalstock\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.intProductQuantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" min=\"0\" disabled>\r\n");
          out.write("                                      <label for=\"subtotalstock\" class=\"active black-text\">Total Stock</label>\r\n");
          out.write("                                    </div>\r\n");
          out.write("                                  </div>\r\n");
          out.write("                                </div>\r\n");
          out.write("                                <div class=\"modal-footer\">\r\n");
          out.write("                                  <button type=\"submit\" class=\"waves-effect waves-white btn-flat purple white-text\">SAVE</button>\r\n");
          out.write("                                  <a href=\"#!\" class=\"modal-action modal-close waves-effect waves-purple btn-flat \">CANCEL</a>\r\n");
          out.write("                                </div>\r\n");
          out.write("                                </form>\r\n");
          out.write("                              </div>\r\n");
          out.write("                        </div>\r\n");
          out.write("                      ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f5[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f5.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f5.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f5);
    }
    return false;
  }
}
